services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: food_app:v1
    ports:
      - "8082:8080"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: food_appdb:v1
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123
      MYSQL_DATABASE: fooddb
      MYSQL_USER: fooduser
      MYSQL_PASSWORD: FoodPassword123
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
